name: .NET CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Show SDK info
        run: dotnet --info

      - name: Restore
        run: dotnet restore EducationPortal.sln

      - name: Build
        run: dotnet build EducationPortal.sln -c Release --no-restore

      - name: Test
        run: dotnet test EducationPortal.sln -c Release --no-build --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test-results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/**
            **/*.trx
